name: Tests

on:
  push:
    branches:
      - "**/*"
      # - "!main"
      # - "!release/current"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Setup Go 1.22
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: build
        run: |
          ./do-release.sh windows
          ./do-release.sh linux
          ./do-release.sh darwin
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: miningPoolCli-*
          retention-days: 7
